#!/bin/bash

# ------------------------------------------------------
# Pacman config
# ------------------------------------------------------
sed -i s/'#Color'/'Color'/g /etc/pacman.conf
sed -i s/'#ParallelDownloads = 5'/'ParallelDownloads = 20'/g /etc/pacman.conf

lsblk
#read -p "Enter disk name: " diskname
diskname=/dev/sda

cfdisk --zero /dev/$diskname

#Fix read partition!

diskpartboot=/dev/sda1
diskpartsys=/dev/sda2
diskhome=/dev/sda3


# ------------------------------------------------------
# Enter partition names
# ------------------------------------------------------
lsblk
#read -p "Enter the name of the EFI partition (eg. sda1 or nvme0n1p1): " diskpartboot
#read -p "Enter the name of the ROOT partition (eg. sda2 or nvme0n1p2): " diskpartsys
#read -p "Enter the name of the HOME partition (eg. sda3 or nvme0n1p3): " diskhome

# ------------------------------------------------------
# Sync time
# ------------------------------------------------------
timedatectl set-ntp true

# ------------------------------------------------------
# EXT 4
# ------------------------------------------------------
mkfs.fat -F 32 /dev/$diskpartboot
mkfs.ext4 /dev/$diskpartsys
mkfs.ext4 /dev/$diskhome

mkdir -p /mnt/{boot/efi,home,var/{cache,log}}

mount /dev/$diskpartboot /mnt/boot/efi
mount /dev/$diskpartsys /mnt
mount /dev/$diskhome /mnt

# ------------------------------------------------------
# Install base packages
# ------------------------------------------------------
pacstrap -K /mnt base base-devel linux linux-firmware linux-headers
# ------------------------------------------------------
# Generate fstab
# ------------------------------------------------------
genfstab -U /mnt >> /mnt/etc/fstab
cat /mnt/etc/fstab
# ------------------------------------------------------
# Install configuration scripts
# ------------------------------------------------------
mkdir /mnt/archinstall
cp arch/conf /mnt/archinstall/
chmod +x /mnt/archinstall/conf
# ------------------------------------------------------
# Add group wheel to sudo
# ------------------------------------------------------
sed -i s/'# %wheel ALL=(ALL:ALL) ALL'/'%wheel ALL=(ALL:ALL) ALL'/g /mnt/etc/sudoers
# ------------------------------------------------------
# Chroot to installed system
# ------------------------------------------------------
arch-chroot /mnt ./archinstall/conf
